version: '3.8'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: intui-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  executor:
    build: 
      context: ./executor-server
      dockerfile: Dockerfile
    environment:
      - APP_ENV=development
      - FS_DATA_PATH=/data
      - GCS_BUCKET=dummy
    volumes:
      - ./data/questions:/data/questions
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  data:
  postgres_data:
