version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    volumes:
      - data:/data/db

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: intui-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
  postgres_data:
  localstack_data:
  localstack_persist:  # Local volume for LocalStack persistent data
