name: Deploy to GCP

on:
  push:
    branches:
      - master
    paths:
      - images/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List directory structure
        run: |
          echo "Current working directory: $(pwd)"
          ls -R

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{secrets.gcp_region}}-docker.pkg.dev

      - name: Build and push Docker image
        working-directory: ./images
        run: |
          docker build -t ${{secrets.gcp_region}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPOSITORY_ID }}/executor-image:latest .
          docker push ${{secrets.gcp_region}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPOSITORY_ID }}/executor-image:latest
